Scientific calculator
razarehan28/JavascriptPractical pull request #1
Opened 2022-04-06 09:01 UTC by razarehan28

2022-04-06 09:24 UTC, desaianiruddh commented on calc.css
> +* {
improve indentation for css

2022-04-06 09:26 UTC, desaianiruddh commented on calc.css
> +	--container-bg-color: #f1f2f4;
use rgb instead of hex code if other else places you've used rgb

2022-04-06 09:26 UTC, desaianiruddh commented on calc.css
> +	padding: 1rem;
use px instead of rem

2022-04-06 09:30 UTC, desaianiruddh commented on calc.css
> +	overflow: scroll hidden;
use either scroll or hidden

2022-04-06 09:32 UTC, desaianiruddh commented on calc.html
> +<!DOCTYPE html>
improve indentation

2022-04-06 09:34 UTC, desaianiruddh commented on calc.html
> +					<div id="second" class="btn">2<sup>nd</sup></div>
Here id name second is not specifying what is second. improve id and class name

2022-04-06 09:36 UTC, desaianiruddh commented on calc.html
> +					<div id="qube-root" class="btn hide">&#8731;x</div>
id name should be cube not qube

2022-04-06 09:42 UTC, desaianiruddh commented on calc.html
> +					<div id="open-parenthesis" class="btn">(</div>
id name should be in camelCase Convention

2022-04-06 10:59 UTC, Rutvi25 requested changes

2022-04-06 10:59 UTC, Rutvi25 commented on calc.css
> +	--dropdownMenu-color: rgb(228, 240, 247);
use - instead of camel case for css variables.
Eg. dropdown-menu-color

2022-04-06 10:59 UTC, Rutvi25 commented on calc.css
> +	margin: 2rem auto;
either use rem or px, at every places

2022-04-06 10:59 UTC, Rutvi25 commented on calc.css
> +	font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
unused fonts can be removed

2022-04-06 10:59 UTC, Rutvi25 commented on calc.html
> +								<img src="./Trigonometry.png" alt="trigo-icon" />
use trigonometry instead of trigo

2022-04-06 10:59 UTC, Rutvi25 commented on calc.html
> +
remove unnecessary line gaps

2022-04-06 10:59 UTC, Rutvi25 commented on calc.js
> +
remove unnecessary line gaps

2022-04-06 10:59 UTC, Rutvi25 commented on calc.js
> +const del = document.querySelector("#clear");
use appropriate name, eg. delete

2022-04-06 10:59 UTC, Rutvi25 commented on calc.js
> +	if (!second.classList.contains("color")) {
improve indentation

2022-04-06 10:59 UTC, Rutvi25 commented on calc.js
> +let Flag = false;
it should be flag instead of Flag

2022-04-06 10:59 UTC, Rutvi25 commented on calc.js
> +			break;
keep only one break

2022-04-06 10:59 UTC, Rutvi25 commented on calc.js
> +		case "round":
break; statement is missing

2022-04-06 10:59 UTC, Rutvi25 commented on calc.js
> +				screen.innerHTML = 3.1428;
Math.PI can be used

2022-04-06 10:59 UTC, Rutvi25 commented on calc.js
> +				screen.innerHTML = 2.7182;
Math.E can be used

2022-04-06 11:27 UTC, ghost commented on calc.css
> +}
for this two classes we can combine the common property in one class and giving the different properties with new classes.

2022-04-07 05:42 UTC, desaianiruddh commented on calc.js
> +        alert("Enter the number you want");
make alert message appropriate. Don't use same alert message each place.. be like "First enter number for log"

2022-04-07 05:46 UTC, desaianiruddh commented on calc.js
> +    case "x-root-y":
it may x raised to y not x root y

2022-04-07 05:53 UTC, desaianiruddh commented on calc.js
> +function memoryMinus() {
memory minus logic is not appropriate. this calculator function not remove number from memory. it save number in memory with negative value

2022-04-07 08:03 UTC, desaianiruddh approved these changes

2022-04-07 08:10 UTC, harshpatel-javascript approved these changes

2022-04-07 09:07 UTC, Rutvi25 approved these changes

2022-04-07 09:12 UTC, harshpatel-javascript approved these changes

2022-04-07 13:39 UTC, sheth-jay requested changes

2022-04-07 13:39 UTC, sheth-jay commented on calc.html
> +                  <div class="btn" id="ceil">Absolute</div>
ids are not matching with their values.e.g. for Ceil button id is absolute.

2022-04-07 13:39 UTC, sheth-jay commented on calc.js
> +  i = 0;
add let or const before declaring a variable.

2022-04-11 11:02 UTC, sheth-jay approved these changes

2022-04-11 11:02 UTC, merged